"""Scenario B MCP tool — ``propose_agent_action``.

ONE custom tool (house tool-count discipline). The agent's loop is:

    propose_agent_action  →  {"approval_id": N}
    get_approval(pk=N)    →  poll until status != "pending"   ← apps/approvals
    get_agent_action(pk=…) → read the result of the executed action

``get_approval`` / ``get_agent_action`` are generated by the enable_mcp factory
from the two CRUDViews, so this app adds no polling tool of its own.

Registration follows the approvals precedent: recorded AND performed, so the MCP
test suite's ``clear_registry_for_tests()`` can be undone.
"""

from __future__ import annotations

import logging
from typing import Any

from asgiref.sync import sync_to_async

from apps.mcp.server import current_context, tool

from .actions import TOOL_NAMES
from .models import AgentAction

logger = logging.getLogger("smallstack.demo_agentops")

_SPECS: list[tuple] = []


def _register(name: str, description: str, schema: dict, **opts: Any):
    def decorator(fn):
        _SPECS.append((name, description, schema, opts, fn))
        tool(name, description, schema, **opts)(fn)
        return fn

    return decorator


def register_agentops_tools() -> int:
    """Re-apply every registration. Idempotent; returns the tool count."""
    for name, description, schema, opts, fn in _SPECS:
        tool(name, description, schema, **opts)(fn)
    return len(_SPECS)


@_register(
    "propose_agent_action",
    (
        "Propose a privileged action for human approval and return its ids. "
        "The action does NOT run now: a human must approve it first. Poll "
        "get_approval(pk=approval_id) until status is no longer 'pending', then "
        "read get_agent_action(pk=action_id) for the execution result. "
        f"tool_name must be one of: {', '.join(TOOL_NAMES)}. "
        "risk='high' additionally requires a superuser to decide."
    ),
    {
        "type": "object",
        "required": ["tool_name", "risk"],
        "properties": {
            "tool_name": {
                "type": "string",
                "enum": TOOL_NAMES,
                "description": "The privileged action to run once approved.",
            },
            "risk": {
                "type": "string",
                "enum": list(AgentAction.Risk.values),
                "description": "Risk tier. 'high' narrows the decision to superusers.",
            },
            "payload": {"type": "object", "description": "Arguments for the action."},
            "agent": {"type": "string", "description": "Agent identity, for the audit trail."},
        },
        "additionalProperties": False,
    },
    write=True,
)
async def propose_agent_action_tool(args: dict[str, Any]) -> dict[str, Any]:
    from . import services

    user = current_context().user

    def _propose():
        try:
            action, req = services.propose(
                tool_name=str(args["tool_name"]),
                payload=args.get("payload") or {},
                risk=str(args["risk"]),
                actor=user,
                agent=str(args.get("agent") or ""),
                source="MCP",
            )
        except ValueError as exc:
            return {"error": str(exc)}
        return {
            "action_id": action.pk,
            "approval_id": req.pk,
            "state": action.state,
            "status": req.status,
            "expires_at": req.expires_at.isoformat() if req.expires_at else None,
            "poll_with": f"get_approval(pk={req.pk})",
        }

    return await sync_to_async(_propose)()
