"""Custom REST endpoints — file and decide approval requests.

    POST /smallstack/api/approvals/requests/create/
    POST /smallstack/api/approvals/requests/<id>/decide/

The CRUD surface (list/detail, auto-generated by enable_api) is the poll
story; these two are the state changes, routed through services so REST
behaves exactly like the web console and MCP.
"""

from __future__ import annotations

from typing import Any, Union

from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404

from apps.smallstack.api import _serialize as _crud_serialize
from apps.smallstack.api import api_error, api_view, register_api_path

from . import permissions, services
from .models import ApprovalRequest
from .views import ApprovalRequestCRUDView

# api_view also accepts (dict, status) tuples — include them in the alias.
ApiResult = Union[JsonResponse, dict[str, Any], tuple[dict[str, Any], int]]


def _serialize(req: ApprovalRequest) -> dict[str, Any]:
    """Match the CRUD GET shape (same field lists) so clients see one schema."""
    return _crud_serialize(
        req,
        ApprovalRequestCRUDView.fields,
        extra_fields=ApprovalRequestCRUDView.api_extra_fields,
        expand_fields=set(ApprovalRequestCRUDView.api_expand_fields),
    )


@api_view(methods=["POST"], require_auth=True)
def api_create_request(request: HttpRequest) -> ApiResult:
    """File a request. Any authenticated caller may file (readonly tokens are
    refused for writes by api_view itself); unknown kinds are a 400 here —
    on a remote surface a typo is likelier than a plan."""
    payload = getattr(request, "json", None) or {}
    kind = str(payload.get("kind") or "").strip()
    title = str(payload.get("title") or "").strip()
    if not kind or not title:
        return api_error("Both 'kind' and 'title' are required.", 400)
    context = payload.get("context")
    if context is not None and not isinstance(context, dict):
        return api_error("'context' must be a JSON object.", 400)
    expires_in_minutes = payload.get("expires_in_minutes")
    expires_in = None
    if expires_in_minutes is not None:
        try:
            from datetime import timedelta

            expires_in = timedelta(minutes=int(expires_in_minutes))
        except (TypeError, ValueError):
            return api_error("'expires_in_minutes' must be an integer.", 400)
    try:
        req = services.request_approval(
            kind=kind,
            title=title,
            actor=request.user,
            description=str(payload.get("description") or ""),
            context=context,
            expires_in=expires_in,
            require_known_kind=True,
            source="REST API",
        )
    except services.UnknownKind as exc:
        return api_error(str(exc), 400)
    return _serialize(req), 201


@api_view(methods=["POST"], require_auth=True)
def api_decide_request(request: HttpRequest, pk: int) -> ApiResult:
    """Decide a pending request. Eligibility (assignees, self-approval, staff
    default) is enforced in the service — assignees may be non-staff."""
    req = get_object_or_404(
        permissions.viewable_requests(request.user, ApprovalRequest.objects.all()), pk=pk
    )
    payload = getattr(request, "json", None) or {}
    if "approved" not in payload or not isinstance(payload["approved"], bool):
        return api_error('Provide {"approved": true|false} (and optionally "note").', 400)
    try:
        req = services.decide(
            req,
            actor=request.user,
            approved=payload["approved"],
            note=str(payload.get("note") or ""),
            source="REST API",
        )
    except services.NotEligible as exc:
        return api_error(str(exc), 403)
    except services.NotPending as exc:
        return api_error(str(exc), 409)
    return _serialize(req)


# --- OpenAPI ---------------------------------------------------------------
# Anchored on the CRUD list route's param-free bare name (build_api_urls
# registers "<url_base dashes>-api-list" ⇒ "approvals-requests-api-list").

_TAG = ["Approvals"]

register_api_path(
    "approvals-requests-api-list",
    subpath="create/",
    methods=["POST"],
    summary="File a new approval request",
    tags=_TAG,
    request_body={
        "required": True,
        "content": {"application/json": {"schema": {
            "type": "object",
            "required": ["kind", "title"],
            "properties": {
                "kind": {"type": "string", "description": "A registered approval kind key."},
                "title": {"type": "string"},
                "description": {"type": "string"},
                "context": {"type": "object", "description": "Kind-specific card payload."},
                "expires_in_minutes": {"type": "integer"},
            },
        }}},
    },
)
register_api_path(
    "approvals-requests-api-list",
    subpath="{id}/decide/",
    methods=["POST"],
    summary="Approve or reject a pending approval request",
    tags=_TAG,
    parameters=[
        {"name": "id", "in": "path", "required": True, "schema": {"type": "integer"}},
    ],
    request_body={
        "required": True,
        "content": {"application/json": {"schema": {
            "type": "object",
            "required": ["approved"],
            "properties": {
                "approved": {"type": "boolean"},
                "note": {"type": "string"},
            },
        }}},
    },
)
