# Generated by Django 6.1 on 2026-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=10),
        ),
    ]
