# Generated by Django 6.1 on 2026-09-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smallstack_approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('requested_by_agent', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending approval'), ('executed', 'Executed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='proposed', max_length=10)),
                ('result', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to='smallstack_approvals.approvalrequest')),
            ],
            options={
                'verbose_name': 'Agent action',
                'ordering': ['-created_at'],
            },
        ),
    ]
