# Generated by Django 6.1 on 2026-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_agentops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaction',
            name='state',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('executed', 'Executed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='proposed', max_length=10),
        ),
    ]
