# Generated by Django 6.1 on 2026-09-25 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smallstack_approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEcho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('approval_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook echo',
                'verbose_name_plural': 'Webhook echoes',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(db_index=True, max_length=120)),
                ('scope', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('duration_hours', models.PositiveIntegerField(default=8)),
                ('state', models.CharField(choices=[('pending', 'Pending approval'), ('granted', 'Granted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=10)),
                ('granted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='smallstack_approvals.approvalrequest')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access request',
                'ordering': ['-created_at'],
            },
        ),
    ]
