# Generated by Django 6.1 on 2026-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=10),
        ),
    ]
